### ISSUE TITLE
Travis is failing (with Python 2.7)

### ISSUE THREAD

**Issue by joshmoore** [ome/ansible-roles#13]

**Comment by sbesson** [comment]
I suspect https://github.com/ome/ansible-roles/issues/9 will also fix this by incidentally bumping Python to 3 and Ansible to 2.6.

If fixing this sooner rather than later is desirable, the ~15 remaining failing roles could be added to an `allow_failures` for now.

**Comment by sbesson** [comment]
See https://github.com/ome/ansible-roles/pull/11#issuecomment-597308236. A few remaining failures to be addressed but most of the upgrade work is now completed.
