### ISSUE TITLE
Proposal for standard molecule scenarios

### ISSUE THREAD

**Issue by manics** [ome/ansible-roles#3]
Following https://github.com/openmicroscopy/ome-ansible-molecule-dependencies/pull/10 molecule will support multiple scenarios.

At present this repo has to handle roles which can't be tested in Travis, for example because they require low-level OS configuration or they require additional resources: https://github.com/ome/ansible-roles/blob/749e53100885a52841d821c7048f38692212537f/.travis.yml#L19-L24

Suggestions:
- All roles must have a `default` scenario which can be run by developers. This would preferably use Docker, but if that's insufficient for testing then Vagrant
- If the `default` scenario uses Docker then optionally provide a `vagrant` scenario
- If the `default` scenario does not work in Travis there must be a scenario named `travis`. For example this may only run a syntax check in molecule.
- Remove the fallback handling in the test script https://github.com/ome/ansible-roles/blob/749e53100885a52841d821c7048f38692212537f/scripts/test.sh#L7-L11

**Comment by joshmoore** [comment]
Nice write up.  It made me wonder if alias'ing would help, i.e. "travis" gets aliased to "docker" or "syntax" regardless. I didn't see any functionality like that in molecule v2. The closest is probably https://molecule.readthedocs.io/en/latest/examples.html#sharing-across-scenarios

**Comment by sbesson** [comment]
Thanks for the insights @manics. I certainly have been contemplating how to use molecule v2 scenarii esp. as multiple scenarii vs multiple platforms.

> - All roles must have a `default` scenario which can be run by developers. This would preferably use Docker, but if that's insufficient for testing then Vagrant

Agreed this matches what has been done so far on the molecule v2 PRs.

> - If the `default` scenario uses Docker then optionally provide a `vagrant` scenario

In some cases

> - If the `default` scenario does not work in Travis there must be a scenario named `travis`. For example this may only run a syntax check in molecule.

Same immediate reaction as https://github.com/ome/ansible-roles/issues/3#issuecomment-423483452, the question is how Travis knows which scenario to execute , I have not checked whether you can filter scenarios e,g,  platform type.

> - Remove the fallback handling in the test script https://github.com/ome/ansible-roles/blob

:+1:
