### ISSUE TITLE
Handle cryptography 3.4

### ISSUE THREAD

**Issue by sbesson** [ome/ansible-roles#87]
[crytpography 3.4](https://pypi.org/project/cryptography/3.4/) released yesterday afternoon broke all the scheduled Molecule builds - see e.g. https://github.com/ome/ansible-role-sudoers/runs/1850565089

```
Collecting cryptography (from ansible==2.8.18->ome-ansible-molecule==0.5.*)
  Downloading https://files.pythonhosted.org/packages/ea/d8/2afd2890fe451a3c109d2bdb6bc4ded55ec43059e524344d5e0004e36412/cryptography-3.4.tar.gz (544kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x1m88z5j/cryptography/setup.py", line 13, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
```

As discussed in https://github.com/pyca/cryptography/issues/5753, the installation can be restored with a more recent version of pip.

This leaves us three options:

- update `molecule.yml` to use ` runs-on: ubuntu-20.04` for the test phase
- update https://github.com/ome/action-ome-ansible-molecule to run `pip install -U pip` before installing the `ome-ansible-molecule` package
- cap `cryptography` to 3.3.x in https://github.com/ome/ome-ansible-molecule for now

**Comment by joshmoore** [comment]
_oy vey_... If I understand correctly, there's no impact on end users? Since rolling `molecule.yml` changes out will require quite a number of commits, it seems like `pip install -U pip` causes the least churn.

**Comment by sbesson** [comment]
I agree solution 2 is the less costly in terms of number of changes at once. I'll test it and report.

Re impact on end users, I think the main one is that `pip install ansible==2.8.*` will now fail on a default virtual environment on CentOS 7 or Ubuntu 18.04. But this is very much an upstream issue and I don't think there is anything we can do except be aware of it and support our community if they encounter the problem.

**Comment by stamak** [comment]
the same with 3.4.1
```
Collecting cryptography>=2.0 (from SecretStorage>=3.2; sys_platform == "linux"->keyring>=15.1->twine==3.1.1->-r /root/project/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/06/ed/cb79cc94ec58d9d92557238fc6c629cd6e07d72334d2de556aecc2211370/cryptography-3.4.1.tar.gz (544kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h9s3g3of/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    
    ----------------------------------------
 (Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h9s3g3of/cryptography/
)
```

**Comment by sbesson** [comment]
See https://github.com/sbesson/action-ome-ansible-molecule/commit/77de5491a705d84e5217df4ab008e82359beb95e now tested via https://github.com/sbesson/ansible-role-sudoers/actions/runs/547386811 for an implementation of option 2

**Comment by sbesson** [comment]
Pushed https://github.com/ome/action-ome-ansible-molecule/releases/tag/v2.0.1 to fix the broken CI pipeline for roles and playbooks immediately. Will keep watching the upstream repositories to see if we need to implement others mitigation/upgrade the platforms.

**Comment by joshmoore** [comment]
Looks like ansible will be doing this as well: https://github.com/ansible-community/antsibull/commit/d9385c930596e1082d3597cb778c891e7d726d71
