### ISSUE TITLE
Molecule 2 upgrade

### ISSUE THREAD

**Issue by sbesson** [ome/ansible-roles#9]
This issue tracks the Ansible roles for which tests remain to be upgraded from Molecule 1 to Molecule 2.

## Status

- [x] ansible-role-prometheus https://github.com/ome/ansible-role-prometheus/pull/6
- [x] ansible-role-hosts-populate https://github.com/ome/ansible-role-hosts-populate/pull/4
- [x] ansible-role-omero-web https://github.com/ome/ansible-role-omero-web/pull/25
- [x] ansible-role-mysql-backup https://github.com/ome/ansible-role-mysql-backup/pull/2
- [x] ansible-role-prometheus-node https://github.com/ome/ansible-role-prometheus-node/pull/3
- [x] ansible-role-postgresql-backup https://github.com/ome/ansible-role-postgresql-backup/pull/1
- [x] ansible-role-devspace **ARCHIVE ???**
- [x] ansible-role-docker-slack-notifier archived
- [x] ansible-role-upgrade-distpackages https://github.com/ome/ansible-role-upgrade-distpackages/pull/4
- [x] ansible-role-selinux-utils https://github.com/ome/ansible-role-selinux-utils/pull/6
- [x] ansible-role-prometheus-postgres https://github.com/ome/ansible-role-prometheus-postgres/pull/7
- [x] ansible-role-prometheus-jmx https://github.com/ome/ansible-role-prometheus-jmx/pull/3
- [x] ansible-role-python-virtualenv-upstream archived
- [x] ansible-role-rsync-server https://github.com/ome/ansible-role-rsync-server/pull/6
- [x] ansible-role-omero-web-runtime (archived)
- [x] ansible-role-fluentd https://github.com/ome/ansible-role-fluentd/pull/3
- [x] ansible-role-redis https://github.com/ome/ansible-role-redis/pull/2
- [x] ansible-role-omero-logmonitor https://github.com/ome/ansible-role-omero-logmonitor/pull/4
- [x] ansible-role-omero-prometheus-exporter https://github.com/ome/ansible-role-omero-prometheus-exporter/pull/5
- [x] ansible-role-cli-utils https://github.com/ome/ansible-role-cli-utils/pull/4
- [x] ansible-role-jekyll-build (archived)
- [x] ansible-role-anonymous-ftp https://github.com/ome/ansible-role-anonymous-ftp/pull/2
- [x] ansible-role-cadvisor https://github.com/ome/ansible-role-cadvisor/pull/5
- [x] ansible-role-analysis-tools https://github.com/ome/ansible-role-analysis-tools/pull/2
- [x] ansible-role-omero-web-django-prometheus https://github.com/ome/ansible-role-omero-web-django-prometheus/pull/2
- [x] ansible-role-local-accounts https://github.com/ome/ansible-role-local-accounts/pull/2
- [x] ansible-role-iptables-raw https://github.com/ome/ansible-role-iptables-raw/pull/2
- [x] ansible-role-celery-docker archived
- [x] ansible-role-munin https://github.com/ome/ansible-role-munin/pull/3

## Upgrade process

Initializing a basic Docker-based Molecule 2 scenario should be achieved using:

```
molecule init scenario -r $(basename $PWD) -s default -d docker
rm -rf molecule/default/INSTALL.rst 
rm -rf molecule/default/tests/__pycache__/
```

Following the creation of the folder, a few steps need to be done:

- migrate/upgrade the top-level `molecule.yml`/`playbook.yml` under `molecule/default`
- migrate/upgrade the `tests` under `molecule/default/tests`
- migrate/upgrade the `tests/tequirements.yml` under `molecule/default` (if applicable)
- in `.travis.yml`, uncap `python: 2.7` and install `pip install "ome-ansible-molecule<0.5"`
- fix `yamllint` an `flake8` warnings thrown by `molecule test`
- commit and open a PR

**Comment by sbesson** [comment]
@manics just noticed an edit on the body of this issue which proposes to archive the following roles: ansible-role-docker-slack-notifier, ansible-role-python-virtualenv-upstream and ansible-role-celery-docker. 

No objections on the latter two from my side. I though `ansible-role-docker-slack-notifier` was used by IDR, but I could not find it. Can you confirm it is not used in any production systems? If so, no objection to archiving as well.

The only other role I would consider for archival is `ansible-role-devspace` since we haven't tested or even used this role in production for at least a year or two.

/cc @joshmoore @jburel

**Comment by manics** [comment]
`ansible-role-docker-slack-notifier` was removed in https://github.com/IDR/deployment/pull/220/commits/cd1ba334994f5efad518bf96310a9f36c5606589
It hasn't been used since the VAE was moved to a completely separate deployment.

Archiving `ansible-role-devspace` sounds fine with me.

**Comment by jburel** [comment]
We have not used ``ansible-role-devspace`` for a while. We will need to update the devspace README if it is archived

**Comment by sbesson** [comment]
Thanks. Opened https://github.com/ome/devspace/pull/163 to initiate the deprecation of the Ansible devspace role. I will also action the archival/deprecation of

- `ansible-role-docker-slack-notifier`
- `ansible-role-celery-docker`
- `ansible-role-python-virtualenv-upstream`

if no vetoes.

**Comment by sbesson** [comment]
All roles listed above have been upgraded and/or deprecated. Finally closing this issue and we can tackle the ones that might have been missing individually
